openapi: 3.0.0
info:
  title: Microservices API
  description: API for user and order management in a microservices architecture.
  version: 1.0.0

servers:
  - url: http://localhost:5001
    description: User Service
  - url: http://localhost:5002
    description: Order Service

paths:
  /register:
    post:
      summary: Register a new user
      tags:
        - User Service
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                email:
                  type: string
                password:
                  type: string
      responses:
        "201":
          description: User registered successfully
        "400":
          description: User already exists

  /login:
    post:
      summary: User login
      tags:
        - User Service
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
      responses:
        "200":
          description: Login successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  access_token:
                    type: string
        "401":
          description: Invalid credentials

  /user/{user_id}:
    get:
      summary: Get user by ID
      tags:
        - User Service
      parameters:
        - name: user_id
          in: path
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: User details retrieved
        "404":
          description: User not found

  /orders:
    get:
      summary: Get all orders
      tags:
        - Order Service
      responses:
        "200":
          description: List of orders

    post:
      summary: Create a new order
      tags:
        - Order Service
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                user_id:
                  type: integer
                product_name:
                  type: string
                quantity:
                  type: integer
      responses:
        "201":
          description: Order created successfully
        "400":
          description: Invalid order request

  /order/{order_id}:
    get:
      summary: Get order by ID
      tags:
        - Order Service
      parameters:
        - name: order_id
          in: path
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: Order details retrieved
        "404":
          description: Order not found
